### ISSUE TITLE
Integrating with LazySizes (lazy loading)

### ISSUE THREAD

**Issue by kerns** [aravishack/Video-Float#4]
Nice work. Any idea how to integrate it with lazy loading 😬 ...where the iframes are not there on document load? Would love to try and integrate your feature.

https://codepen.io/kerns/full/vLoWqZ

**Comment by aravishack** [comment]
One solution is to try out Native iframe loading. This have a limited browser support now. You can checkout more details here : https://web.dev/iframe-lazy-loading/
